version: "3.7"

x-default-app: &default-app
  RELEASE_NAME: local
  LOCAL_MONGODB_SERVICE_HOST: mongo
  LOCAL_MONGODB_SERVICE_PORT: 27017
  LOCAL_RABBITMQ_SERVICE_HOST: rabbitmq
  LOCAL_RABBITMQ_SERVICE_PORT_AMQP: 5672
  LOCAL_RABBITMQ_SERVICE_PORT_HTTP_STATS: 15672
  RABBITMQ_USERNAME: user
  RABBITMQ_PASSWORD: bitnami

networks:
  app-tier:
    driver: bridge

services:
  app:
    environment:
      <<: *default-app
    volumes:
      - .:/app
    build: .
    networks:
      - app-tier

  mongo:
    image: mongo:4.2.5
    restart: always
    ports:
      - "5001:27017"
    networks:
      - app-tier

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    networks:
      - app-tier

  hutch:
    restart: always
    environment:
      <<: *default-app
    volumes:
      - .:/app
    build: .
    networks:
      - app-tier
    command: bundle exec hutch
    depends_on:
      - rabbitmq

  sneakers:
    restart: always
    environment:
      <<: *default-app
    volumes:
      - .:/app
    build: .
    networks:
      - app-tier
    command: rake sneakers:run
    depends_on:
      - rabbitmq
