apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
  - image: ghcr.io/ikenom/ecommerce-backend
    sync:
        infer:
        - 'app/**/*.rb'

deploy:
  helm:
    releases:
    - name: shopify-client
      namespace: default
      artifactOverrides:
        image: ghcr.io/ikenom/ecommerce-backend
      chartPath: k8s
      skipBuildDependencies: true
      valuesFiles:
        - ./k8s/values.yaml