apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  RELEASE_NAME: {{ .Release.Name }}
  RABBITMQ_USERNAME: {{ .Values.rabbitmq.auth.username }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.auth.password }}