name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Build and push image
        run: |
          docker login ghcr.io -u $GITHUB_ACTOR --password-stdin <<< ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          docker build . --tag ghcr.io/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}:$GITHUB_SHA
          docker push ghcr.io/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}:$GITHUB_SHA

      - name: Pacakage and push Helm
        run: |
          helm package -u --app-version $GITHUB_SHA chart
          docker pull quay.io/helmpack/chart-releaser:v1.1.1
          docker run -v $(pwd):/app quay.io/helmpack/chart-releaser:v1.1.1 cr upload -p /app -o ${{ github.event.repository.owner.login }} -r ${{ github.event.repository.name }} -t ${{ secrets.GITHUB_TOKEN }}

      - name: Create Helm index and push to GH pages
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email '$GITHUB_ACTOR@users.noreply.github.com'
          git fetch
          git checkout gh-pages

          helm repo index --url https://${{ github.event.repository.owner.login }}.github.io/${{ github.event.repository.name }} --merge index.yaml .
          git commit -am "Updating helm package"
          git push

      - name: Install Python
        uses: actions/setup-python@v1

      - name: Install bump2version
        run: |
          pip install --upgrade bump2version

      - name: Bump Helm version
        run: |
          bump2version --commit --current-version 0.2.7 patch chart/Chart.yaml
          git push