name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          docker login ghcr.io -u $GITHUB_ACTOR --password-stdin <<< ${{ secrets.GITHUB_TOKEN }}
          docker build . --tag ghcr.io/ikenom/${{ github.repository }}:$GITHUB_SHA
          docker push ghcr.io/ikenom/${{ github.repository }}:$GITHUB_SHA